### ISSUE TITLE
Alternative Projects Landing Page View

### ISSUE THREAD

**Issue by watrall** [matrix-msu/kora#435]
Would be nice to have an alternative tile-based project landing page.  To go along with this, would be good if these project tiles had some sort of visual to differentiate the projects.  Perhaps users can upload a project image that is used in the tile somehow?

**Comment by watrall** [comment]
something like this? 
![card](https://user-images.githubusercontent.com/109138/49820910-2cbeb080-fd47-11e8-95e9-bd6d5e105348.png)

**Comment by austintruchan** [comment]
I like this

**Comment by fritosxii** [comment]
Or at the very least make this apart of the dashboard tiles

**Comment by watrall** [comment]
would love to be able to add to these project tiles to dashboard *and* have an alternative project page view (tile-based instead of just list-based)

**Comment by austintruchan** [comment]
#### An Alternative Projects / Tile View has been added: https://projects.invisionapp.com/d/main#/console/11107725/338151176/preview

- There are now two icons on the projects page to switch between list and tile view. 
- There is now an option to add project imagery in the edit project page, and when you create a new project.
- There is a new option in the preference page to set the tile view to be the default view
https://projects.invisionapp.com/d/main#/console/11107725/242678599/preview
- I also wanted a way to view the project imagery (if its added) when you're on the single project page, so there is now a very subtle header that showcases project imagery on the single project page: https://projects.invisionapp.com/d/main#/console/11107725/235019913/preview

#### Dashboard Project block with imagery added: https://projects.invisionapp.com/d/main#/console/11107725/235445415/preview
- There is also a way to now set the project block "style" to either show the project description, or the project imagery when creating or editing a project block. https://projects.invisionapp.com/d/main#/console/11107725/327005040/preview

@watrall Let me know if you have questions. If you approve, I'll make a more comprehensive ticket for these changes and pass to development.

**Comment by watrall** [comment]
what is project has a long name?  In list view, ong names are accommodated.  But in this view, they are not.  Need to figure out a way to display longer names.

**Comment by austintruchan** [comment]
> I also like the dashboard tile design over the project page tile design. Can you try to use the dashboard tile design on the project landing page?

Do you mean the fact the dashboard version includes the quick icon links? Or the fact the content area is wider and the cards are wider? The cards will be a bit wider on the projects page on the actual site, as the comps content area is less wide than what is live. I don't think we can make the content area as wide as the dashboard's without having the page feel awkward, since it will then break the grid that is there.

**Comment by austintruchan** [comment]
> what is project has a long name? In list view, ong names are accommodated. But in this view, they are not. Need to figure out a way to display longer names.

An example of when a project name is longer can now be seen at: https://projects.invisionapp.com/d/main#/console/11107725/338151176/preview

The project tiles will be a bit wider on the live site as well, and will allow for longer project titles.

**Comment by watrall** [comment]
I personally prefer to the version of the tiles with the quick link icons.  However, the issue with these (and the three dot menu, for that matter) is that we have no control over the color of the project image the user uploads.  Its possible that the user will upload something that results in very, very low contrast with the icons, making them unusable.   

Can you come up with a solution for that?

**Comment by austintruchan** [comment]
Yes, the solution is to provide a dark overlay on top of the imagery for each tile, darkening it enough so that the icons appear clear enough even if the image is a purely white image. This is how it currently is at: 
https://projects.invisionapp.com/d/main#/console/11107725/338151176/preview

One of the tiles now has a purely white image so you can see an example of the icon remaining visible.
We've done this solution in the past, with mbira and other projects. 

Shall I add the quick link icons to the project page then?

**Comment by watrall** [comment]
sure, let's see how it looks.

**Comment by austintruchan** [comment]
Updated at: https://projects.invisionapp.com/d/main#/console/11107725/338151176/preview

**Comment by watrall** [comment]
ok, I was totally, totally wrong.  too many icons.

**Comment by austintruchan** [comment]
Lol. Okay, updated again: https://projects.invisionapp.com/d/main#/console/11107725/338151176/preview

Once we approve, I'll make a more comprehensive ticket for these changes and pass to development.

**Comment by watrall** [comment]
what happens when you favorite a project?  Where are those favorites accessible?

**Comment by austintruchan** [comment]
At the moment there is no way to actually "favorite" a project. The user can add project dashboard blocks on the dashboard page, and also edit the layout of the projects in the custom tab on the all projects page to put their preferred projects at the top of the list. 

I do have ideas for a favoriting / pinning system, but at the moment the comps do not have anything like that. Should I make a to do to add a favoriting system to maybe tackle someday?

**Comment by fritosxii** [comment]
Archiving some future requested features
