### ISSUE TITLE
Customize Login Page Background Image

### ISSUE THREAD

**Issue by watrall** [matrix-msu/kora#442]
Would be nice to customize the background image on the login page.  Instead of letting the user upload an image (which is always problematic), maybe have choice of 6 or so images that have all been optimized and sized properly (that we create and are part of all kora installs).  Choice could be available in My Preferences.

**Comment by austintruchan** [comment]
The My preferences page has been updated to include a section to change login page background (Note: images that are there are just placeholders): https://projects.invisionapp.com/d/main#/console/11107725/242678599/preview

It may take time to find suitable options that work well aesthetically and that don't clash with the text on the page. The ideal Background images should be very light / white to work the best. 

With that said, what sort of options do we want to include? Nature? Architecture? Feel free to provide some and I can mock them up to get an idea of what they look like. I'll also look for some if and when I'm bored and have downtime.

**Comment by austintruchan** [comment]
New potential login background, "Mountain" https://projects.invisionapp.com/d/main#/console/11107725/338353244/preview

**Comment by watrall** [comment]
The images must be cultural in nature.  They should subtly speak to our commitment to Africa and cultural heritage.  This is certainly something that we can come up with collectively.  As option would be to draw on our own Flickr images.  Not sure if there is anything that we could use there, but it would be a good place to start.  You could also pull from my Flickr feed (https://www.flickr.com/photos/18695692@N00/).

**Comment by fritosxii** [comment]
Archiving some future requested features
