### ISSUE TITLE
Batch List Upload

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/kora#530]
Allow a batch way to add list values to a list field

EDIT: We also want to add a way to export these values from a list field

**Comment by austintruchan** [comment]
Ok. I will.

**Comment by fritosxii** [comment]
@austintruchan Somewhere on this card, need options for deleting all options, and for copying all options to clipboard

<img width="895" alt="Screen Shot 2019-10-16 at 12 41 41 PM" src="https://user-images.githubusercontent.com/4040076/66940119-61a82d80-f012-11e9-90a3-30ceba38290c.png">

**Comment by austintruchan** [comment]
Updated this invision screen to show where to put these new buttons: https://projects.invisionapp.com/d/main?origin=v7#/console/11107725/292425673/preview

Told you I would do this, on March 29th. I am a man of my word.

**Comment by fritosxii** [comment]
Now you just gotta make it

**Comment by fritosxii** [comment]
Tell me how it looks big Aus: https://chyron-20.matrix.msu.edu/projects/57/forms/102/fields/List_Field_57_102_/options#

@austintruchan

**Comment by fritosxii** [comment]
Just design layout, the links don't do anything yet

**Comment by fritosxii** [comment]
Styled, and applied to most lists.

Last two things are list sub fields within a combo list and in the creation of Field Value Presets
