### ISSUE TITLE
Selecting current year for the date

### ISSUE THREAD

**Issue by 0Redfeather** [matrix-msu/kora#535]
I am making a "Created On" field to describe the date that an archaeological collection was created. The way I set up the field now makes the available dates go up to 2030 in case a new collection is made in the next 10 years. Is there a way to make it so that the current year is the cutoff (end year) for the date field type?

**Comment by fritosxii** [comment]
Currently there is not. But that seems like a useful feature, so I will definitely squeeze it in for the next release!

**Comment by fritosxii** [comment]
Tracking: #536

**Comment by fritosxii** [comment]
@0Redfeather This feature will now be available in the official re-release of kora.
