### ISSUE TITLE
Global Search bugs

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/kora#634]
[4402_001.pdf](https://github.com/matrix-msu/kora/files/3616705/4402_001.pdf)

- [x] Fix the projects dropdown

- [x] Add loading icon for executed search

- [ ] See if speed improvements are possible

**Comment by asheill** [comment]
I can only see "NEH 2 - Contemporary Dynamics of Buh Kunta Qadiri Comm" in the dropdown list

**Comment by fritosxii** [comment]
Projects dropdown was an issue with that chunk of code calling the old project ID column. The fix will restore the dropdown with all of a User's projects

**Comment by fritosxii** [comment]
Loading icon makes it more obvious that system is still being searched.

Also not really much we can do to improve the speed for so many Forms, while maintaining the combination of records from different forms, and doing so with pagination. Loading icon will at least make it clear to user at least that search is in progress
