### ISSUE TITLE
Association Deletion Warnings pt 2.

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/kora#638]
Figure out when a user would see their record data, and if it has forward associators that no longer exist, warn the user

**Comment by fritosxii** [comment]
Archiving some future requested features

**Comment by watrall** [comment]
why are these being closed?

**Comment by fritosxii** [comment]
@watrall Part of it is for cleanup, but mostly I'm archiving future features where the feature is no longer planned for development, or the priority of the request has fallen off. The features that survived are mostly ones that add improvements to core functionality, that would ideally be developed in the near future. A couple of them are pet projects

All features that are archived, and will remain archived so once they become a higher priority, we can reopen them.

If you have a discrepancy in either issues closed, or those left open, let me know!

**Comment by watrall** [comment]
as long as the ticket doesn't disappear entirely.  Though, I would far prefer that they were moved to a "maybe sometime in the future" project....that way, they are immediately visible (though, not in production)
