### ISSUE TITLE
Problem with Error Screen

### ISSUE THREAD

**Issue by watrall** [matrix-msu/kora#641]
Issues with error screen:

- email is listed as root@localhost.com
![error](https://user-images.githubusercontent.com/109138/65191901-6691b580-da43-11e9-8a0a-f66b1db6cfe8.jpg)

**Comment by fritosxii** [comment]
What installation is this taking place on? That's probably because the admin user was created without a provided email

**Comment by fritosxii** [comment]
Updated the admin email for the main installations

**Comment by watrall** [comment]
was main kora.dev
