### ISSUE TITLE
issue with importing forms

### ISSUE THREAD

**Issue by beyeraut** [matrix-msu/kora#678]
I’m working on documentation of Kora for Ethan and I am having a few issues with importing forms. I’ve successfully downloaded a form from ‘Museum Collections’ (Museum_Collections__18_) and it started to upload into ‘Campus Archaeology Program’ (Campus_Archaeology_Program_14_). However, the page showed the working/loading disc icon for quite some time so I refreshed the page. It now shows the form (Trial Import Form), but when I try to view the form it brings me to the whoops something went wrong page. Is it possible to have this form removed from the Campus Archaeology Program project?

Now when I try to upload the form into my test project, it shows the working/loading icon for a few seconds before disappearing and remaining on the form information tab of the import form setup page. I also had Zach, another person working on documentation attempt to upload a form and it did the same thing for him (remaining on the import form setup page).

Is there a different way to import a form other than going to the project page, using the dropdown menu, and clicking the ‘Import Form Setup’ button? Thanks!

**Comment by watrall** [comment]
FYI  - @beyeraut is working in Anthropology Kora.

**Comment by fritosxii** [comment]
@beyeraut Sorry for the delay, looking into this now

**Comment by fritosxii** [comment]
Ok, reimporting combo list fields was broken when it tried to create the combo list table. I hot fixed this into the anthropology kora for now so you can continue wokring

**Comment by beyeraut** [comment]
Hello again, it is doing the exact same thing again. It is stuck on the loading symbol for importing a form and when I refresh it shows the working/loading icon for a few seconds before disappearing and remaining on the form information tab of the import form setup page. 

I am also now getting another issue when I tried to create a new form (in the Museum Collections) to export and then import into a new project. "kora-Error 500"

**Comment by fritosxii** [comment]
The latter error was an issue with that first form breaking. 

What form in `Museum Collections` are you exporting? So I make sure I test the right one.

**Comment by beyeraut** [comment]
At this time, I just tested it out with Form 2 (Unique Form ID: Form_2_5_92_) that just has text fields worked from exporting from Museum Collections into my test page (Unique Project ID: ZZTest_apainter_5_) and it worked! I also just tested if I could make a form and it let me make one in both my test page and the Museum Collections page.
