### ISSUE TITLE
Batch Assigning Field Values on Firefox

### ISSUE THREAD

**Issue by 0Redfeather** [matrix-msu/kora#680]
Hello, I'm working with the KORA documentation and ran into an issue trying to batch assign values to specific records in the Form Records & Search page. 

On Chrome, I am able to select, edit and batch assign the records no problem, but on Firefox the selection button is to the right of the record and unselectable. I've include screenshots to demonstrate this. 

![Chrome Screenshot](https://user-images.githubusercontent.com/42443178/70470284-ac857500-1a98-11ea-83d3-49788d5f929e.png)

![Firefox Screenshot](https://user-images.githubusercontent.com/42443178/70470289-af806580-1a98-11ea-86e9-d7c90f1ea248.png)

**Comment by fritosxii** [comment]
Fixed the display bug causing this issue. Should available in the launch update next week.
