### ISSUE TITLE
Issue with duplicating records

### ISSUE THREAD

**Issue by beyeraut** [matrix-msu/kora#681]
On the Anthropology Kora (Museum Collections project; Museum_Collections__18_) I have been unable to have records duplicate properly. I have tried both duplicating while creating records and duplicate already created records. When I try to have duplicates made when creating the original record, no duplicates are created. When I try to have several (I've been trying 5) duplicates made of an existing record, only one duplicate is created. I tried this in multiple forms (Form 3 and Object forms) within this project.

**Comment by fritosxii** [comment]
Record duplication is repaired in development, but has not made its way to Master yet. This should be repaired when the installation is next updated
