### ISSUE TITLE
Issue with custom option in user preferences

### ISSUE THREAD

**Issue by beyeraut** [matrix-msu/kora#683]
When I change my user preferences for the 'Single Project Tab Selection' from alphabetical to custom it no longer displays the forms within projects. Instead it lists the name of the project several times (see attached image). It does this for each of my projects. 
![single project tab selection issue](https://user-images.githubusercontent.com/14350563/72626032-ea877b80-3917-11ea-96df-fe1b4ab4e8b6.png)

**Comment by fritosxii** [comment]
Bug confirmed in development build. Looking into it

**Comment by fritosxii** [comment]
Yeah, we were saving the project and displaying that, instead of the actual forms themselves. This will be resolved in the next update

**Comment by watrall** [comment]
what is the timeline for the next update?

**Comment by fritosxii** [comment]
Planning to start updating local installations on Monday.
