### ISSUE TITLE
Issue with Importing Projects

### ISSUE THREAD

**Issue by beyeraut** [matrix-msu/kora#693]
When I try to import a project into the Anthropology Kora, I run into several issues. It allows me to upload my project file, and input the project information, however, after I press 'Import Project & Information' the loading symbol appears for a second, then disappears, and nothing changes on the page. I am not brought to the newly imported project.

When I look at my project list after doing this, the new project exists, but there is no token assigned to the new project, and no forms from the project are imported. I assume that the previous forms and fields are imported when you import a project. Does this process also import records from the project?

![project_import_issue](https://user-images.githubusercontent.com/14350563/73754612-a0353580-4732-11ea-9263-0b9c44316c89.png)

**Comment by fritosxii** [comment]
Import project should bring in the entire project structure, and all included forms, so the missing forms is an issue. Can you send me the import file?

Token and records are not imported with the project

**Comment by beyeraut** [comment]
@fritosxii can you provide your email address? GitHub doesn't accept the .kProj file type.

**Comment by fritosxii** [comment]
Got your email, I'll take a look and see what I can find.

**Comment by fritosxii** [comment]
Ok, so the issue isn't exactly with the import, but with the export. Specifically the combo list field you tried importing `Name and Birthday` was broken. One of the sub fields was named `Name ` instead of `Name`. I will be adding a fix to combo list create to make sure spaces around the sub field name are trimmed off

**Comment by fritosxii** [comment]
@beyeraut I think the best way for you to retest would be to edit that combo field and fix the sub field names, reexport the project, and then reimport it

**Comment by beyeraut** [comment]
@fritosxii I am still getting the same result after editing the combo field and re-exporting and re-importing. I also tried exporting and importing the Campus Archaeology Program project (Unique Project ID: Campus_Archaeology_Program_14_) and it did the same thing (does not bring me to the new project, does not assign a token, no forms or records are brought in)

**Comment by fritosxii** [comment]
Ok, digging deeper

**Comment by fritosxii** [comment]
Ok so I reexported CAP and imported in my test environment. The reason your second attempt with the new file failed was because the first attempt with the old file broke.

I cleared out the bad data from the DB. If you try to export and reimport CAP, it should work now.

**Comment by beyeraut** [comment]
@fritosxii It worked! Thank you so much for figuring this out!
