### ISSUE TITLE
Unarchiving Projects notification

### ISSUE THREAD

**Issue by beyeraut** [matrix-msu/kora#696]
When I **unarchive** a project in the Anthropology Koa, the pop-up that appears says "Project Successfully Archived" instead of Unarchived. 
![unarchive popup](https://user-images.githubusercontent.com/14350563/73945813-e4efd680-48c2-11ea-864d-5115033f2c94.png)

**Comment by fritosxii** [comment]
Found and repaired the notifications. Will be repaired next time I update!
