### ISSUE TITLE
Generated List issues - extra blank option being generated

### ISSUE THREAD

**Issue by 0Redfeather** [matrix-msu/kora#697]
**Describe the bug**
When entering values for a generated list, if you press "Enter" after typing in your value then a blank option appears along with the list option that you've entered. This does not occur when pressing the **Add** button to add your list options 

**To Reproduce**
1. Go to a generated list field when entering data for a record
2. Type in any list option for the generated list field
3. Hit enter on the keyboard

**Expected behavior**
Expected to see only the list options I have entered, but another blank option appears when pressing "Enter". 

**Screenshots**
For the option marked by red, I pressed "Enter" on my keyboard to submit those options. for "Option 7" and "Option Press Add", I pressed the "Add" button in Kora.  
![Generated list bug](https://user-images.githubusercontent.com/42443178/73965175-a4ec1c00-48e1-11ea-8799-479b2424a51a.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home, 64-bit, version 1903]
 - Browser [FireFox]
 - Version [72.0.2 (64 bit)]

**Smartphone (please complete the following information):**
 - Device: [ ]
 - OS: [ ]
 - Browser [ ]
 - Version [ ]

**Additional context**
I was also unable to view records after attempting to create a generated list. I will create another issue for that.

**Comment by fritosxii** [comment]
Wasn't able to reproduce exactly but I did find pressing Enter in the box or clicking Add will just add blank options. Going to update JS to not allow blanks
