### ISSUE TITLE
Generated List preventing viewing/editing of records

### ISSUE THREAD

**Issue by 0Redfeather** [matrix-msu/kora#698]
**Describe the bug**
I entered values into a generated list field for a record, but I get an error page every time I try to create a record and go to the *Form Records & Search* page. Since I am working on the Kora documentation, this particular form has every field type on it. I filled every field with a value, but the generated list is the only one giving me grief. I know this because making the generated list unviewable allows me to see all of my records again (See screenshots below). I am also unable to edit the record with the generated list value, however, getting an error page. I am wondering if the fact that I included a combo list that also has a generated list on the the same page is part of the issue. 

**To Reproduce**
1. Enter data into a record for a generated list field
2. Click 'Create New Record'

**Expected behavior**
Expected to see the values I entered for a generated field in the records page. 

**Screenshots**
1. When the Generated List field is viewable: 
![Viewable generated list](https://user-images.githubusercontent.com/42443178/73967395-cfd86f00-48e5-11ea-9cc7-21cc0445ad60.png)
2. Viewing records in the form gives me an error
![Whoops something went wrong](https://user-images.githubusercontent.com/42443178/73967428-e383d580-48e5-11ea-9c4a-62ff5d99eeff.png)
3. Making the Generated list unviewable
![GL unviewable in results](https://user-images.githubusercontent.com/42443178/73967502-03b39480-48e6-11ea-8cdf-9ade434f9234.png)
4. Allows me to see the records again (though I am unable to edit any records with the generated list values that I entered) 
![Allows me to look at the record](https://user-images.githubusercontent.com/42443178/73967550-17f79180-48e6-11ea-9313-111dca24e80f.png)
5. I am unsure, but wonder if the fact that I have a combo list with a generated list on the same page has anything to do with this.
![Other List](https://user-images.githubusercontent.com/42443178/73967585-2e9de880-48e6-11ea-911a-46a5f9976166.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home, 64-bit, version 1903]
 - Browser [FireFox]
 - Version [72.0.2 (64 bit)]

**Smartphone (please complete the following information):**
 - Device: [ ]
 - OS: [ ]
 - Browser [ ]
 - Version [ ]

**Additional context**

**Comment by fritosxii** [comment]
We discovered this bug last week as well :) Generated list data was not being properly formatted for save

I pushed a fix and repaired the data in the form you were testing so you should be able to use generated list info again.
