### ISSUE TITLE
Question regarding installation: subdirectory

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#711]
This isn't really a feature request or a bug report, but rather a couple more general questions about installation.

I have been able to install this in an msu.domains environment, but currently can only get it to be accessible in a ".../public" subdirectory (curretly, https://geyerbri.msu.domains/kora/public). There are two related issues with this. First, what would I do to install this in such a way that the interface would be found at, say, https://geyerbri.msu.domains/kora/ or https://geyerbri.msu.domains? 

Second, with my installation right now, going to the link above for "..../kora" reveals the contents of that directory. Presumably there's a way to set things up so that these wouldn't be visible, but I'm guessing that this has to do with however I get the interface to be available at a specific domain or subdomain, so once I can do that, this won't be a problem anymore.

Just to add one additional comment, is it possible this is related to the "RewriteBase" setting in .htaccess, or another setting in that file?

**Comment by fritosxii** [comment]
`public` is the directory that actually serves the application, which is why you need to point to it. 

Say you had a directory `/var/www/kora/public`, to use https://geyerbri.msu.domains/kora/ as your main (or even https://geyerbri.msu.domains), you would have to configure the server to have that url point at the public folder.

If you do that it should also prevent web access to the kora folder above public

**Comment by fritosxii** [comment]
Rewrite base is more affected by what the url is and not by server folder structure.

i.e. https://geyerbri.msu.domains/kora/ will always be `/kora`, https://geyerbri.msu.domains/kora/public will always be `/kora/public`

**Comment by geyerbri** [comment]
Ok I understand now. I will try to figure out how to do this.

**Comment by fritosxii** [comment]
Closing for now. Feel free to reopen if you have other issues related

**Comment by geyerbri** [comment]
Ok I have another question about this. Currently, I do not know how to configure the server to point https://geyerbri.msu.domains/kora/ at public_html/kora/public (where https://geyerbri.msu.domains is pointed at public_html/).

So instead, I've set up a subdomain at https://kora.geyerbri.msu.domains, which is pointed at public_html/kora/public. Going to that subdomain URL loads up the content of public_html/kora/public, while still displaying that subdomain URL (as expected). I have also successfully set up a 301 redirect for the URL "https://geyerbri.msu.domains/kora," which reloads as "https://kora.geyerbri.msu.domains" in the address bar. 

_HOWEVER_, when I go to "https://geyerbri.msu.domains/kora/public/", the URL remainss like this. I've tried setting up a 301 redirect specifically for this address, to get it to redirect/reload as "https://kora.msu.domains," but this always fails.

(All of the above, I have done with cPanel tools for my server environment and not through writing an .htaccess file on my own)

Is this failing because I am misunderstanding the limits of redirects, such that there's no way for me to sort-of 'hide' the ........domains/kora/public/ URL and have it always redirect to display as "https://kora.geyerbri.msu.domains"? Or is what I am trying to do possible, but perhaps only via actual .htaccess file writing (which I know very little about)?

**Comment by fritosxii** [comment]
The specifics of this question might be out of my wheelhouse. I might have some ideas of possible things to do, but not that I would consider reliable.

@goekesmi Might have better opinions on this.

**Comment by geyerbri** [comment]
@goekesmi walked me through things and I now understand all of this. Thank you both for your help.
