### ISSUE TITLE
Question regarding installation: permissions

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#712]
The installation documentation described in the README, after running the installation code:

> Give READ access to the web user for kora and ALL sub-folders.
>Give WRITE access to the web user for the following directories and ALL their sub-folders

In this case, what does "web user" refer to? I was able to get my installation (https://geyerbri.msu.domains/kora/public) to work by setting permissions with:

```
chmod -R 755 kora/
chmod -R g+s kora/
chmod -R g+w kora/bootstrap/cache/
chmod -R g+w kora/storage/
chmod -R g+w kora/public/assets/javascripts/production/
```

But, because I don't understand what "web user" is referring to in the documentation, I have no idea if this was the correct approach/process, or whether or not it was overkill.

**Comment by fritosxii** [comment]
I should change the text on it, but basically the web user is actually the `group user` in unix

**Comment by geyerbri** [comment]
Thank you, this has gotten me pointed in the right direction.

Just right now, setting different permissions, the login page was accessible when I set the permissions as 705, rather than 750, so it may be that it's `other user` rather than `group user`? 

I'm going to play around further with setting "write" permissions on the specified folders for either `group` or `other` and see if there's a difference.

**Comment by fritosxii** [comment]
So the unix bits are `user`, `group`, `public`. As far as I understand it, at least at matrix, we use a `group` for accessing apache and managing site permissions.

With 755 as our default, 7 gives full permissions to the `user`, and 5 gives read/execution permissions to the `group` and the `public`. Then when we go to 775, we are giving the `group` write permissions to certain folders

**Comment by geyerbri** [comment]
I just realized I never followed-up here. I know that my specific server environment required execute permissions for `public` rather than `group`, but since the documentation I'm writing is for general case, I'm hesitant to restrict it to just one or the other.

And even if I _could_ adequately explain the differences to a layperson via the guide and tell them how to figure out which one works for their case, I don't know how to personally test the directories that require write permissions. So at this point I'm just directing users to use 755 recursively for the install, `g+s` recursively for the install as well as a precaution, and then 777 on the three directories, also recursively. If you have any thoughts/advice on this (especially about `g+s` and about running all these recursively), I would absolutely want to hear that. But if not, you can close this issue I think.

**Comment by fritosxii** [comment]
The problem with giving write permissions to public, is that anyone with a link to a particular file can modify that file and don't even have to be apart of kora.

More so write permissions for the 3 folders needs to be given to Apache, or whatever server application is used to handle web requests. In php linux, it is common for Apache to be that server and the group permissions are usually used to manage Apache's permissions. 

I think we can use the 755 and 775 stuff as examples but what's more important is that the user understands that the 3 write permissions need to go to web server

**Comment by geyerbri** [comment]
Do you know of a way I could test an installation such that, when the the read/execute have been given to `other` but the write permissions have **not** been given to Apache (likely `group`), the install doesn't work properly? I'm looking for a hopefully-simple action, like updating the configuration file or something similar. This would let me confirm that `775` works in my case, so that I can more confidently assume it will work in other instances as well (and I will make sure the documentation explains the part about permissions for the web server).

I am being extra thorough here because of the previously-noticed behavior with setting read/execute permissions. The install's login page loaded properly when I gave `other` execute-level access (`5`) and `group` was set to `0`, but did not load when those were reversed.  So I would like to independently verify the permissions for `group` and `other`. Then, when I write the documentation, I'll note the connection between either of those and "web server" or "web user" as appropriate.

**Comment by fritosxii** [comment]
Easiest way to test write permissions is to create a record with a file field in it

**Comment by geyerbri** [comment]
Ok now I am thoroughly confused. 

I have confirmed that the current permissions on the install directory and subdirectories are `755` (I specifically checked `storage/` too). But I was able to successfully create a record with a .jpg attached to it. 

I even found this uploaded .jpg file in my File Manager; all the directories down to where it is are `755` but the file itself is `644`.

**Comment by geyerbri** [comment]
I am confident I now understand permissions well enough and won't need further help with this.
