### ISSUE TITLE
reCAPTCHA problem on sign-up page

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#714]
**Describe the bug**
When trying to use the new account sign-up page on my Domains-installed version, reCAPTCHA is giving an error "ERROR for site owner: Invalid key type". I'm getting this after realizing that, once server-side installation is complete, there's several settings required in the configuration area once logged in as admin. That area asks for reCAPTCHA keys, but doesn't specify v2 or v3, or which version of v2 (checkbox, invisible, or Android) to use. So far v3 and v2 invisible haven't worked.

**To Reproduce**
1. Go to 'Admin account'
2. Click on 'Kora Configuration File' in menu under Management
3. Enter reCAPTCHA keys obtained from that service
4. Go to 'create new account' page for the install with another browser/incognito (https://geyerbri.msu.domains/kora/public/register)
5. Error at bottom

**Expected behavior**
Expected either v3 or v2 invisible reCAPTCHA to work properly for login, but neither does.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera (Chromium based)
 - Version 66

**Smartphone (please complete the following information):**

**Additional context**

**Comment by geyerbri** [comment]
Quick addendum: I'm currently playing around with subdomains/redirects/other things that may break the link above. If that link is broken when you try to access it, let me know here and I'll put everything back ASAP.

**Comment by fritosxii** [comment]
kora currently uses v2 checkbox

**Comment by fritosxii** [comment]
Not knowing the standards of recaptcha, is it worth upgrading to v3?

@watrall @geyerbri

**Comment by watrall** [comment]
honestly, I haven't the faintest clue.  I wonder if there is an aspect of futureproofing?  I suspect that @goekesmi might have thoughts?

**Comment by geyerbri** [comment]
Is there any further reason to keep this open (or me assigned)?

**Comment by goekesmi** [comment]
The only comment I have is that as an external service, eventually, the client side of it will need to be upgraded, as the external service evolves.  When we do that work is mostly decided by the external service, recaptcha.
