### ISSUE TITLE
New User invitations not working as expected

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#724]
**Describe the bug**
When a user who has been invited uses the provided URL to sign-up, after completing the sign-up page, they are still expected to wait for a second email for account confirmation. 

**To Reproduce**
1. Using admin account, invite an email address
2. Using that email address, follow the "Accept Invite" link for creating account (this link appears to have an authentication/activation credential included in the URL)
3. After completing the account creating info and submitting...
4. See error: the user is presented with notice that their account still requires activation.

**Expected behavior**
I expect an invited user to not require activation after filling in the sign-up information. If this expectation is in error, it may just be my assumption, but given that the generated "Accept Invite" link in the invitation email appears to be customized for each invite and contains the exact same token that gets generated in the additional "Activate Account" email, I think my assumption is correct.

**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version 67

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by fritosxii** [comment]
You assumption is correct. We currently still require them to go through the full activation process. We do not have a forked path of the user create process for invited users.

**Comment by geyerbri** [comment]
Ok that makes sense.

I guess I would just note then, the current set-up seems to generate that activation token on the initial invitation email's "Accept Invite" URL. I do not know whether or not this is secure and so do not know whether or not this would be better changed for the time being and then adjusted back if/when you ever have the forked path.

**Comment by fritosxii** [comment]
Ok, I see what's happening. That does seem confusing. Let me see if there is anything I can do to mitigate it so they don't need to activate twice

**Comment by fritosxii** [comment]
Ok, so if you pull in the new changes, inviting a new user via the email method should no longer require them to manually activate. The activation happens automatically now since the email is already verified.
