### ISSUE TITLE
Multiform Record importing freezes up

### ISSUE THREAD

**Issue by 0Redfeather** [matrix-msu/kora#738]
**Describe the bug**
@beyeraut and I have attempted to import records into multiple forms within a project using csv, xml and json files. Whenever I upload a file and hit upload, the **Upload Record Import Files** turns gray and seems to freeze. 

I had created 3 text fields and one list field in both forms labeled as field 1, 2,3 and 4. My goal was to import 3 records in both forms using these field.  I believe I followed the correct format, but the option to match field options does not appear. Perhaps I filled out the the templates for csv, xml and json files out incorrectly or am misunderstanding something else?

**To Reproduce**
1. Go to '_Import Multi Form Records_ page'
2. Click on 'Add new file and select forms you want to import'
3. Scroll down to '**Upload Record Import Files** button and press it'

**Expected behavior**
Expected Kora to begin importing the records or to allow me to perform field matching.

**Screenshots if Applicable**
![Multiform Records Bug](https://user-images.githubusercontent.com/42443178/79577076-230f3080-8092-11ea-8db4-49ac81ceadc7.png)

![Screenshot of how I tried to import records](https://user-images.githubusercontent.com/42443178/79578356-1db2e580-8094-11ea-9c76-03ed09cefb42.png)

Can't upload a json file, so I've included a txt version of the json file - 
[json_working_example.txt](https://github.com/matrix-msu/kora/files/4493455/json_working_example.txt)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [75.0]

**Additional context**

**Comment by fritosxii** [comment]
I will take a deeper dive on this later, but @0Redfeather , the json you provided has one standout error. Each record needs to be separated by a comma (i.e. `[{record_info},{record_info},{record_info}]`).

Let me know if this fixes it. Regardless I'll look into the issue to further expand error reporting on the issue.

**Comment by watrall** [comment]
@0Redfeather @fritosxii Is Kora exporting the records with the lack of commas?  Or is there something else?

**Comment by fritosxii** [comment]
@watrall My understanding is they built the JSON file manually and did not add the commas. The commas are present in data that kora exports. Unless you export 1 record, then there is no need to add a trailing comma. Either way php JSON_encoder is doing the heavy lifting of generating the json coming out of kora

**Comment by watrall** [comment]
roger, roger

**Comment by 0Redfeather** [comment]
@fritosxii Thanks, I couldn't figure out what was wrong when I was using the validator. I did fix it, however, I am still getting the same issue. @watrall I simply wrote up the records myself and had forgotten to put the commas in. 

Here's a screenshot of what I put in this time, which still brought up the same error: 
![import records json - fixed](https://user-images.githubusercontent.com/42443178/79587517-a768b000-80a0-11ea-986f-792c7e189542.png)

**Comment by fritosxii** [comment]
Ok, I will investigate and see what I can find out!

**Comment by fritosxii** [comment]
Another question for clarification, are you uploading 1 record for 2 forms? If so, each form needs its own record file. I'm guessing that is where the error is happening. I need to figure out a way to make that error visible.

**Comment by fritosxii** [comment]
I.e. you will need two json files, even if they are essential duplicate files with different names

**Comment by 0Redfeather** [comment]
Yes, that was definitely the error that I was running into. I actually got the upload to work when I submitted 2 record files. Though I ran into some records not importing, but that's probably just a different issue that I can hopefully work out myself. 

So, I guess I was just misunderstanding the purpose of a multiform record import. It's meant to import multiple sets of records into multiple forms, not just a set of records into multiple forms. Correct me if I'm wrong, but I will update the documentation with this. Thanks!

**Comment by fritosxii** [comment]
Correct, this feature lets you upload records to multiple forms in your project at the same time. Each Form needs its own record file. The main benefit to this method is that if you have associations between records in different forms, you can define and complete those connections using this feature

**Comment by fritosxii** [comment]
Let me know if you need further clarification on the feature. If not, feel free to close the issue!
