### ISSUE TITLE
Kora Configuration File Key Order

### ISSUE THREAD

**Issue by beyeraut** [matrix-msu/kora#743]
**Describe the bug**
When entering the site key and secret key (Recaptcha Public Key & Recaptcha Private Key) the terminology and order in which they are listed does not match between Google reCAPTCHA and Kora Configuration File. It may cause future issues with users with them not being listed in the same order or using the same terminology. 

**To Reproduce**
1. Go to 'menu icon in top right corner'
2. Click on 'Management'
3. Click on 'Kora Configuration File'
4. First two options for filling in information for Recaptcha Public Key & Recaptcha Private Key

**Expected behavior**
Currently, Google reCAPTCHA lists the site key, then the secret key. It would be user friendly to list these in the same order with similar terminology instead of 'Recaptcha Private Key' & 'Recaptcha Public Key.' 
<img width="574" alt="Screen Shot 2020-04-24 at 12 30 44 PM" src="https://user-images.githubusercontent.com/14350563/80235245-70a61300-8627-11ea-8a50-488802198ffa.png">

<img width="402" alt="Screen Shot 2020-04-24 at 12 25 05 PM" src="https://user-images.githubusercontent.com/14350563/80235198-5ff59d00-8627-11ea-80da-60fb068ce75f.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina v 10.15.3
 - Browser: Chrome
 - Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by geyerbri** [comment]
This was something that I took note of as well and think would be nice if it were changed.

**Comment by watrall** [comment]
@fritosxii Is this an easy fix?  While not technically a bug, its a serious UX issue.

**Comment by fritosxii** [comment]
Yeah, it should be easy. It's on my todo list, just haven't got there yet

**Comment by watrall** [comment]
thumbs up
