### ISSUE TITLE
Change files name upload warning.

### ISSUE THREAD

**Issue by watrall** [matrix-msu/kora#748]
**Is your feature request related to a problem? Please describe.**
Currently, when the user tries to upload a file that contains unsupported characters, they get a warning that says "‘Invalid file with illegal characters provided."  This is unfortunately not helpful at all because there is no indication as to what character are supported and what are "illegal" (which isn't a wonderful word to mean unsupported or not accepted.  

**Describe the solution you'd like**
Change the warning text to something a little friendlier and helpful.  Possibly "Unfortunately, the name of the file you are trying to upload contains characters currently not supported by Kora.  Currently, only file names are limited to a-z, A-Z, 0-9, ., -, and _ are supported.  Please change your file name accordingly and re-upload."

I will also note this in several locations in the official documentation.  However, changing the warning message to something more helpful is equally important.

**Comment by fritosxii** [comment]
@watrall So the way the error design is laid out currently, we have kept field errors typically very short. Long sentences seem to break the design:

<img width="907" alt="Screen Shot 2020-05-11 at 10 26 35 AM" src="https://user-images.githubusercontent.com/4040076/81573289-44ea9300-9372-11ea-9a88-ba6d1f273afa.png">

Would it be fine to have something shorter and more direct like this

<img width="865" alt="Screen Shot 2020-05-11 at 10 27 31 AM" src="https://user-images.githubusercontent.com/4040076/81573320-4fa52800-9372-11ea-887c-f2bb20e37c31.png">

**Comment by watrall** [comment]
I think the second option is fine.  Question - is that the styling for error messaging?

**Comment by fritosxii** [comment]
Yes, we use the orange letting for input errors

**Comment by fritosxii** [comment]
This is true for all input fields that error out, not just record inputs.

Last note, is that most inputs themselves are also highlighted along with the error message. The file upload does not have this highlight currently because of the custom input

**Comment by watrall** [comment]
Does Kora have other error messaging styles for non-input errors?  The reason I ask is that I would argue for error messaging consistency across the entire platform.  At the very least, I would very strongly suggest for a change in text color in this case.  the orange on white has serious readability issues.  Very low contrast.  Also, orange doesn't scream **error**

**Comment by watrall** [comment]
Slight edit to revised text: "Filename not supported (filenames limited to a-z, A-Z, 0-9, ., -, and _ )

**Comment by fritosxii** [comment]
Ok text updated
