### ISSUE TITLE
Text Wrapping issue on Generated Lists

### ISSUE THREAD

**Issue by beyeraut** [matrix-msu/kora#754]
**Describe the bug**
On the Anthropology Kora, I have been using the 'generated list' option to provide pre-written citations while also allowing new citations to be added. When a citation is long, the text does not wrap within the list box. I'm not sure if this is an issue only for Generated Lists or for all list types. 

**To Reproduce**
1. Go to forms and add the generated list field. Under advanced options, type out a long sentence or two. 
2. Go to enter a record for that form and see that the list options are not contained within the list boxes. 

**Expected behavior**
Expect the text for each option to wrap within the box. 

**Screenshots**
<img width="875" alt="References_text_wrap" src="https://user-images.githubusercontent.com/14350563/81984583-03244b80-9603-11ea-983c-d5dc7b4d5e79.png">

**Comment by watrall** [comment]
@fritosxii - can you tell me where this bug is in the queue
