### ISSUE TITLE
Install guide improvements

### ISSUE THREAD

**Issue by Denubis** [matrix-msu/kora#764]
Just noting them down here.

1) Make sure to instruct people to have https running
2) I suspect that you're going to want to instruct people to make a virtualserver to public, so that /kora isn't served by the webserver
3) I think there are some a2enmod commands for the rewrite that need to be specified. 

I've managed to make a snakeoil cert going and the login page is being served with css and js, but now https://10.0.0.27/kora/public/login is 404ing 

```
    #RewriteBase #add base url ex: www.website.com[/this part is your base url for this file up to "public"]
    RewriteBase /kora
```
Once I fixed allowoverride on (I've migrated to nginx these last few years. LAMP is very rusty) 
    `RewriteBase /kora/public` worked. 

getting to the point of trying to upload an image:
```
[Wed Jun 17 04:30:51.212552 2020] [php7:error] [pid 15649] [client 10.0.0.15:36190] script '/var/www/html/kora/index.php' not found or unable to stat, referer: https://10.0.0.27/kora/public/
2[Wed Jun 17 04:34:24.467364 2020] [php7:notice] [pid 17299] [client 10.0.0.15:37982] Function not found: imagecreatetruecolor, referer: https://10.0.0.27/kora/public/projects/1/forms/1/records/create
[Wed Jun 17 04:34:24.467529 2020] [php7:notice] [pid 17299] [client 10.0.0.15:37982] Function not found: imagecreatetruecolor, referer: https://10.0.0.27/kora/public/projects/1/forms/1/records/create
[Wed Jun 17 04:34:24.467540 2020] [php7:notice] [pid 17299] [client 10.0.0.15:37982] Function not found: imagecreatetruecolor, referer: https://10.0.0.27/kora/public/projects/1/forms/1/records/create
```

Are there other plugins, modules, or whatnots I need to install?

**Comment by watrall** [comment]
@Denubis - We have robust user documentation over at https://chi-initiative.github.io/kora-documentation/

This includes a lot more detailed discussion of installation requirements on a LAMP stack (https://chi-initiative.github.io/kora-documentation/getting-started/system_requirements/).  I think what you note above is addressed there (or so @geyerbri tells me)  

NB - I'd characterize the documentation as being in beta (has a lot of rough edges that need to be smoothed).  If you want, you are welcome to contribute to the documentation (minor or major).  Please note, the documentation is geared towards generally untechnical users....hence the langueg being very descriptive, step by step, and assuming no existing knowledge.  

At some point in the near future, we're going to better integrate this documentation with the Kora repo (as well as Kora itself).
