### ISSUE TITLE
Deleted users still being 'detected'

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#765]
**Describe the bug**
On my Kora installation, I had added a bunch of dummy user accounts to test for a past bug (since fixed). I just deleted all of those users, but then realized I needed one of them still, so I went to re-add it and got the error "[email] already exists!"

**To Reproduce**
1. Go to User Management in an admin account
2. Add and confirm a user account
3. Delete that account
4. Attempt to re-add the account to see the error

**Expected behavior**
I expect user accounts that are deleted to be purged, so they could be re-added at a future time.

**Screenshots**
The error:
![Capture3](https://user-images.githubusercontent.com/5496867/85148601-53a05180-b21e-11ea-98a3-f9bbab5e8620.PNG)

My user list:
![Capture4](https://user-images.githubusercontent.com/5496867/85148629-5c912300-b21e-11ea-912d-c927a74cead8.PNG)

Showing that the deleted user also doesn't show up when searched for:
![Capture5](https://user-images.githubusercontent.com/5496867/85148671-67e44e80-b21e-11ea-9e16-12aed333cbb7.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Opera
 - 68

**Additional context**
I don't when the version of Kora I currently have installed was compiled.

**Comment by fritosxii** [comment]
Brian, are you able to get a list of what usernames/emails are in the database? I want to see what the general state of the users table is after having deleted all the accounts

**Comment by geyerbri** [comment]
Looks like the user(s) remained in the database after deleting:

![Capture3](https://user-images.githubusercontent.com/5496867/85301853-601ee700-b476-11ea-90f9-b299cef40d67.PNG)

**Comment by fritosxii** [comment]
Interesting. I'll do some testing to see what is going on

**Comment by geyerbri** [comment]
After working through setting up Gitlab integration, I discovered that the list of users did not update with all of the newly created accounts, which hasn't ever been an issue before. I now think this may be an issue either with some mistake I may have made when originally installing, or some later date, and not an issue with Kora.

**Comment by fritosxii** [comment]
After my investigation, user deletion worked on multiple installations. Based on that and what you found, it sounds like something else is going on.

**Comment by geyerbri** [comment]
I hope you're fine with me closing this. I don't know what was going on, but after reinstalling I haven't had any issues. If I notice it again, I'll bring it back up.

**Comment by fritosxii** [comment]
Yeah we can close it for now, but yes definitely document if it happens again and at the very least we can put that information out there as something to be aware of when setting up kora.
