### ISSUE TITLE
Gitlab integration issues

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#766]
**Describe the bug**
I am unsure if this is a bug _per se_.

I am having trouble integrating Gitlab with a Kora installation. The Kora Configuration File page asks for "Gitlab Client ID" and "Gitlab Client Secret," but I do not find anything in my Gitlab-hosted Continuous Integration (CI) account matching these descriptors. Searching for OAuth [EDIT: I originally stated this was for OAuth2, but I have instead been working with instructions for OAuth] features in Gitlab led me to the "Applications" section. 

I left "Gitlab Client" as "https://gitlab.com" because my CI account is hosted there and is not a local installation.

After setting an application up and putting in my Kora installation url as the redirect URI (selecting all scopes, including "read_user"), I copied Gitlab's "Application ID" to the Kora field "Gitlab Client ID" and copied Gitlab's "Secret" to the Kora field "Gitlab Client Secret."

When trying to log into my Kora installation using Gitlab, I am appropriately directed to gitlab.com to log in. However, after successfully logging in, I receive an error page from gitlab.com, "An error has occurred. The redirect URI included is not valid."

I have also deleted and recreated the registered application in gitlab as [url]/home, [url]/home/, [url]/projects, and [url]/projects/ to test each of them. None have worked.

I am opening this here to figure out how to troubleshoot this problem, because I do not know if this is an issue with what I've provided to Kora, or instead what I've provided to Gitlab.

**To Reproduce**
Please read above.

**Expected behavior**
With everything set up properly, I would expect Gitlab to handle the login and then properly redirect back to my Kora installation.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Opera
 - 68

**Comment by geyerbri** [comment]
One additional bit: in the Gitlab setup under "Applications", the box for "Confidential" is checked.

Gitlab's description of this setting:
"The application will be used where the client secret can be kept confidential. Native mobile apps and Single Page Apps are considered non-confidential."

**Comment by fritosxii** [comment]
For the callback URL in gitlab, you need to put `{kora_url}/login/gitlab/callback` (i.e. `https://www.myKora.com/login/gitlab/callback`)

**Comment by geyerbri** [comment]
This worked, thank you.

**Comment by geyerbri** [comment]
I have an additional question regarding gitlab integration. When setting up the application in gitlab, there is an option to specify whether the linked application is "confidential." This is its explanation of this option:

> The application will be used where the client secret can be kept confidential. Native mobile apps and Single Page Apps are considered non-confidential.

I have been assuming that Kora would be considered "confidential", but I think I should be asking this just to make sure.

**Comment by fritosxii** [comment]
By this definition kora would be considered a confidential application.

**Comment by geyerbri** [comment]
Thanks!
