### ISSUE TITLE
Name conflict for font files

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#769]
**Describe the bug**
This isn't a bug, _per se_, but does interfere with extracting Kora to a directory on a Windows machine. Two sets of font files have names where their differences are only case-related:

public/assets/fonts/Ubuntu-Medium.tff and public/assets/fonts/ubuntu-medium.tff 

and

public/assets/fonts/Ubuntu-Regular.tff and public/assets/fonts/ubuntu-regular.tff

**To Reproduce**
1. Download zip of Kora to a Windows machine
2. Extract the zipped files into directory
3. See the name conflicts

**Expected behavior**
I would expect each file to have unique names. Many others in that same folder have had "2" added to the end of them to overcome the naming conflict.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by fritosxii** [comment]
Yeah, windows and MacOS do not support files with different capitalizations. Linux however handles this without issue, so for the mean time we will just list it as a known issue
