### ISSUE TITLE
Allow admin accounts to unlink Gitlab authentication

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#772]
**Is your feature request related to a problem? Please describe.**
After testing Gitlab integration, I think it would be useful in certain circumstances for admin accounts to be able to unlink a Kora account from its Gitlab-affiliated account. 

For instance, in a case where an administrator needs to revoke access to a Kora user account, but not delete it outright; in such a case, setting a new password (already an option for admins) would only partially inhibit access, since the Gitlab login would still be possible. This is distinct from when an administrator unchecks the box for "Active" on the account, because such a change would only require the user to try logging in again, receive the automated email for activating their account, and then completing that process.

**Describe the solution you'd like**
Currently there is the option, "Remove Gitlab Account" for a user editing their own profile. I would like to see this option available for admins when they are editing other users' accounts.

**Describe alternatives you've considered**
1. One alternative would be for things to stay the way they are, not implementing this request. As stated in the example above, this would allow an account that admins think should be restricted from having access to still have access.

2. Currently, unchecking the "Active" box for an account requires it to re-activate, via email and with the provided URL or token. This applies to user accounts set up through Gitlab authentication. So a second alternative could be to have the act of unchecking this box also unlink the Gitlab account. However, I do not know if unlinking a Gitlab account should be an outcome of removing an account's "Active" status. I think it's probably better if this action were separate from the "Active" setting.

**Comment by fritosxii** [comment]
It definitely is a bug that users can re-activate a second time after being deactivated. I will fix this regardless.

If I were to do this, would it still be useful to have a Remove Gitlab link?

**Comment by geyerbri** [comment]
I think it would be yes. It will give admins greater flexibility in troubleshooting any issues that might arise with users trying to log into their accounts.

**Comment by geyerbri** [comment]
This also has me thinking about what happens when a user tries to use Gitlab to sign up, when Gitlab OAuth has not been configured for the Kora install. Currently, the Kora Configuration File has gitlab.com as the default and requires text in this box before an admin can save the page. This means it will, in cases where gitlab OAuth hasn't been set up, users who try to use Login with Gitlab at the sign-in page will be redirected to gitlab.com, as if the integration works. After logging into their Gitlab account, they are greeted with a Gitlab-side error screen:

![Capture3](https://user-images.githubusercontent.com/5496867/85740279-7e335400-b6cf-11ea-9457-ae7f2911788a.PNG)

This led down a further rabbit hole, with what might happen if the Gitlab client box said something else. See #

**Comment by fritosxii** [comment]
If there are no OAuth keys set, the Login with Gitlab button won't (shouldn't appear) appear

**Comment by geyerbri** [comment]
Oh then this is another bug, because it is definitely there at the moment:

Config page:
![Capture3](https://user-images.githubusercontent.com/5496867/85751010-349b3700-b6d8-11ea-9b97-37ec44e866e5.PNG)

Login screen:
![Capture3](https://user-images.githubusercontent.com/5496867/85751140-4d0b5180-b6d8-11ea-8042-491fef38dfb8.PNG)

Is it possible that, if the credentials were added and then later removed, the button would persist?

**Comment by fritosxii** [comment]
I think I look for it to be blank and maybe insert_gitlab_here values are accidentally being added. I will fix that bug at least. And probably add a more example style URL instead of the actual gitlab url

**Comment by geyerbri** [comment]
I just tried to remove the keys from my second test install, but the text fields are required, and I now remember that, for my first install, I had to rewrite  in "insert_gitlab_xxx_here" myself. This should probably be addressed as well: allow admins to remove Gitlab functionality entirely.
