### ISSUE TITLE
Text other than URL in Gitlab Client box causes issues

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#773]
**Describe the bug**
The Gitlab Client box is a required text box on Kora Configuration File page. Changing the default url to a simple string (e.g. "test") and then saving, then logging out, then trying to use the Gitlab login feature, leads to a simple page refresh. When then logging into Kora with Kora credentials, the first page displayed is a 404 error:

![Capture3](https://user-images.githubusercontent.com/5496867/85741811-bb4c1600-b6d0-11ea-8d80-d2cffce7c6cb.PNG)

More complex text in the Gitlab Client box breaks things entirely. When I entered "(e.g. https://gitlab.com)" - this was to test alternative text in the box, to keep from having the Gitlab login button automatically lead to gitlab.com (see #772)  - and hit save on the configuration page, the page reloaded completely blank:

![Capture3](https://user-images.githubusercontent.com/5496867/85742465-43322000-b6d1-11ea-8d76-200e3986f198.PNG)

There were 2 dozen console errors, but all of them say, "Unchecked runtime.lastError: The message port closed before a response was received."

Trying to go to my Kora installation always loads a completely blank page. The only way I know to fix this is to manually edit the .env file, removing the offending line of text from `GITLAB_CLIENT=` and setting it to something less 'complex,' or to a URL.

**To Reproduce**
Steps to reproduce the 404 error:
1. Go to Kora Configuration File page as an admin.
2. Change the Gitlab Client text to a non-url text string of letters and numbers and save.
3. Log out
4. Click the "Login with Gitlab" button.
5. After page refresh, log in with a Kora account.
6. See error.

Steps to reproduce the blank page error:
1. Go to Kora Configuration File page as an admin.
2. Change the Gitlab Client text to a more complex string (I've been using `(e.g. https://gitlab.com)` but am assuming other strings with similar symbols and spaces would do).
3. Click save.
4. See the blank page.

**Expected behavior**
I would expect a complex string of characters, symbols, and spaces to either not be valid for the box, or not not break the installation when saved. But I also think this text box should default to something that won't give the appearance of the Gitlab login working, so it might be useful to take this into account when fixing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version 68

**Additional context**
See [this comment](https://github.com/matrix-msu/kora/issues/772#issuecomment-649602620) at #772

**Comment by geyerbri** [comment]
Tested this with the most-recent build, and it looks like things have been partially fixed. I can now see that the URL box appears to be detecting http/https protocol and toggling the Gitlab sign-in button accordingly. So changing the text in the URL box to something without the protocol and the option disappears.

But it is still possible to type in spaces into the URL text box (and the client key and secret boxes as well) which, when saved, results in the blank page and requires fixing via manually editing .env.

**Comment by fritosxii** [comment]
Ok, I see the issue. It's a general ENV issue that I didn't check for, but because spaces aren't allowed in ENV files (unless surrounded by quotes), the ENV breaks. I will add a validation check that removes or fails on spaces.
