### ISSUE TITLE
Manual Activation URL in Email

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#778]
**Describe the bug**
In the activation email auto generated for users who sign up for a Kora install, there are two URLs. One - "Activate Accout" - properly handles the activation process via a URL with an embedded activation token.

But the other is described as taking users to a page where they will paste in their activation token manually. However, when following this link, instead of arriving at a page with an option for pasting in the token, I am instead taken to the main user registration page.

**To Reproduce**
1. Go to Kora user registration page (via "Need to Sign Up?" link on login page)
2. Fill in info to register a new user and click "Sign Up"
3. Check email account for auto-generated email.
4. Follow the link provided for manual activation.
5. Will arrive on registration page.

**Expected behavior**
I expect this link to take a user to a page where they can paste in their activation code manually.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version 68

**Comment by fritosxii** [comment]
Emails are being removed from kora
