### ISSUE TITLE
"Mail From Name" problem with email configuration

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#779]
**Describe the bug**
Emails sent through Kora's smtp do not have the specified Alias/Identifier attached (specified via the "Mail From Name" on the Kora Configuration File page).

So far I have checked this via Gmail and MSU Email clients, as well as emails sent to MSU Email which are then forwarded to a Gmail account.

**To Reproduce**
1. Set up smtp for Kora install, including the "Mail From Name" text
2. Use Kora to send an email, such as by inviting a new user, by signing up as a new user, or going through the lost password process.
3. Check email inbox for the auto-generated email.
4. Note that the received email does not display the defined Alias/Identifier.

**Expected behavior**
I expect the received email to have the defined Alias/Identifier.

**Screenshots**
Sent to Gmail:
![Capture3](https://user-images.githubusercontent.com/5496867/87694695-7c9ffd80-c75c-11ea-8764-5fa7dceec11a.PNG)

Sent to MSU Mail:
![Capture7](https://user-images.githubusercontent.com/5496867/87694712-8295de80-c75c-11ea-9e69-a3480ad8e7e6.PNG)

Sent to MSU Mail and routed to Gmail:
![Capture5](https://user-images.githubusercontent.com/5496867/87694731-89bcec80-c75c-11ea-825b-2763823efbcf.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera
 - Version: 68

**Comment by fritosxii** [comment]
Emails are being removed from kora
