### ISSUE TITLE
Search Results - Pagination Chevrons

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/kora#783]
The chevrons within the pagination buttons on search result pages all currently point down.

Example: https://kora.enslaved.org/keywordSearch/project/16/forms/23?keywords=&method=0

**Comment by fritosxii** [comment]
<img width="612" alt="Screen Shot 2020-08-31 at 10 58 05 AM" src="https://user-images.githubusercontent.com/4040076/91748386-e863eb80-eb8d-11ea-82ab-c25e7855986a.png">

**Comment by fritosxii** [comment]
![Screen Shot 2020-08-31 at 1 29 16 PM](https://user-images.githubusercontent.com/4040076/91748428-f9146180-eb8d-11ea-8e0a-e1d884cd4466.png)
