### ISSUE TITLE
Form Records Search Results - ID Ascending Descending Sort Error

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/kora#784]
When viewing the Form Records results page and then selecting either ID Ascending or ID Descending from the sort by dropdown, the page seems to error out. This was seen here: https://kora.enslaved.org/keywordSearch/project/16/forms/23?keywords=&method=0 

I'm not sure if that is a global kora issue or just that specific form, but figured I'd report it.

**Comment by fritosxii** [comment]
![Screen Shot 2020-08-31 at 1 28 16 PM](https://user-images.githubusercontent.com/4040076/91748337-d5e9b200-eb8d-11ea-9c96-89f6789f10c8.png)

**Comment by fritosxii** [comment]
Sorting was broken on keyword search result pages
