### ISSUE TITLE
Current month, day, year not working

### ISSUE THREAD

**Issue by jeffjb4488** [matrix-msu/kora#805]
**Describe the bug**
When trying to set a date field (mm / dd / yyyy) the default options "current month", "current day", "current year" do not stay when the form is updated and are left blank. I do not know if this is a settings issue with our database in particular or with KORA as a whole.

Any help would be appreciated - thank you,

Jeff B.

**Comment by fritosxii** [comment]
Bug confirmed

**Comment by fritosxii** [comment]
Fixed a bug that prevented Current month, day, year from being set for the default date field values. Inherently fixed them being used in record creation as well.
